// 2026년 1월 5주차 성수동 실제 팝업스토어 데이터
import type { PopupStore } from "@/types";

export const SAMPLE_POPUPS: PopupStore[] = [
  {
    id: "1",
    name: "Ongredients Popup",
    name_korean: "온그리디언츠",
    brand: "Ongredients",
    category: "cosmetics",
    tags: ["beauty", "skincare", "experience"],
    location: "성수동",
    address: "서울 성동구 연무장길 65",
    coordinates: { longitude: 127.0558, latitude: 37.5437 },
    period_start: "2026-01-31",
    period_end: "2026-02-23",
    operating_hours: "11:00 - 20:00",
    description: "온그리디언츠 뷰티 체험 팝업. 스킨케어 제품 체험 가능.",
    description_ja: "オングリディエンツのビューティー体験ポップアップ。スキンケア製品の体験が可能。",
    description_en: "Ongredients beauty experience popup. Try skincare products.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1596462502278-27bfdc403348?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "2",
    name: "PUCCA x Chef Jung Ji-sun",
    name_korean: "뿌까 x 정지선 쉐프",
    brand: "PUCCA x Funny Joo",
    category: "food",
    tags: ["character", "chef", "collaboration", "F&B"],
    location: "퍼니주",
    address: "서울 성동구 서울숲2길 44-13",
    coordinates: { longitude: 127.0433, latitude: 37.5461 },
    period_start: "2026-01-30",
    period_end: "2026-02-01",
    operating_hours: "11:00 - 21:00",
    description: "뿌까와 정지선 셰프의 콜라보 팝업스토어. 한정 메뉴 판매.",
    description_ja: "プッカとチョン・ジソンシェフのコラボポップアップ。限定メニュー販売。",
    description_en: "PUCCA x Chef Jung Ji-sun collaboration popup. Limited menu available.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "3",
    name: "GMC Grand Launch",
    name_korean: "GMC 그랜드런치",
    brand: "GMC",
    category: "lifestyle",
    tags: ["car", "automobile", "experience", "luxury"],
    location: "성수동 일대",
    address: "서울 성동구 성수이로 88",
    coordinates: { longitude: 127.0568, latitude: 37.5427 },
    period_start: "2026-01-29",
    period_end: "2026-02-01",
    operating_hours: "10:00 - 19:00",
    description: "GMC 자동차 체험 팝업. 신차 전시 및 시승 가능.",
    description_ja: "GMC自動車体験ポップアップ。新車展示と試乗が可能。",
    description_en: "GMC car experience popup. New car exhibition and test drive available.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "4",
    name: "Luvum at Musinsa Beauty Space",
    name_korean: "러븀",
    brand: "Luvum",
    category: "cosmetics",
    tags: ["beauty", "skincare", "musinsa"],
    location: "무신사뷰티스페이스",
    address: "서울 성동구 왕십리로 83-21 무신사뷰티스페이스",
    coordinates: { longitude: 127.0434, latitude: 37.5442 },
    period_start: "2026-01-28",
    period_end: "2026-02-08",
    operating_hours: "11:00 - 21:00",
    description: "러븀 뷰티 브랜드 체험 팝업. 무신사뷰티스페이스에서 진행.",
    description_ja: "ラブムビューティーブランド体験ポップアップ。ムシンサビューティースペースで開催。",
    description_en: "Luvum beauty brand experience popup at Musinsa Beauty Space.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "5",
    name: "Journey of Butterfly",
    name_korean: "나비의 여정",
    brand: "Fashion Exhibition",
    category: "fashion",
    tags: ["fashion", "exhibition", "art"],
    location: "성수동",
    address: "서울 성동구 연무장9길 7",
    coordinates: { longitude: 127.0552, latitude: 37.5441 },
    period_start: "2026-01-22",
    period_end: "2026-02-28",
    operating_hours: "10:00 - 19:00",
    description: "패션 전시회 '나비의 여정'. 아트와 패션의 만남.",
    description_ja: "ファッション展示会「蝶の旅」。アートとファッションの出会い。",
    description_en: "Fashion exhibition 'Journey of Butterfly'. Art meets fashion.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "6",
    name: "Macallan Harmony Collection",
    name_korean: "맥캘란 하모니컬렉션",
    brand: "Macallan",
    category: "food",
    tags: ["whisky", "alcohol", "premium", "experience"],
    location: "오므오트",
    address: "서울 성동구 서울숲4길 18 오므오트",
    coordinates: { longitude: 127.0445, latitude: 37.5455 },
    period_start: "2026-01-20",
    period_end: "2026-02-08",
    operating_hours: "12:00 - 21:00",
    description: "맥캘란 하모니 컬렉션 위스키 체험 팝업. 시음 및 구매 가능.",
    description_ja: "マッカランハーモニーコレクションウイスキー体験ポップアップ。試飲と購入が可能。",
    description_en: "Macallan Harmony Collection whisky experience popup. Tasting and purchase available.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1569529465841-dfecdab7503b?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "7",
    name: "Sierra Design at EQL",
    name_korean: "시에라디자인",
    brand: "Sierra Design",
    category: "fashion",
    tags: ["outdoor", "fashion", "apparel"],
    location: "EQL성수",
    address: "서울 성동구 연무장길 7 EQL성수",
    coordinates: { longitude: 127.0556, latitude: 37.5439 },
    period_start: "2026-01-19",
    period_end: "2026-02-08",
    operating_hours: "11:00 - 21:00",
    description: "시에라디자인 아웃도어 패션 팝업스토어.",
    description_ja: "シエラデザインのアウトドアファッションポップアップストア。",
    description_en: "Sierra Design outdoor fashion popup store.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1445205170230-053b83016050?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "8",
    name: "My Golden Kids at Marple Custom",
    name_korean: "금쪽같은내새끼",
    brand: "SBS",
    category: "entertainment",
    tags: ["character", "TV", "merchandise"],
    location: "마플커스텀스토어",
    address: "서울 성동구 성수이로7길 30 마플커스텀스토어",
    coordinates: { longitude: 127.0589, latitude: 37.5442 },
    period_start: "2026-01-19",
    period_end: "2026-01-31",
    operating_hours: "11:00 - 20:00",
    description: "SBS 금쪽같은내새끼 캐릭터 굿즈 팝업스토어.",
    description_ja: "SBS「金の子供たち」キャラクターグッズポップアップストア。",
    description_en: "SBS 'My Golden Kids' character goods popup store.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1513475382585-d06e58bcb0e0?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "9",
    name: "PUBG Seongsu Winter School",
    name_korean: "펍지성수 윈터스쿨",
    brand: "PUBG",
    category: "entertainment",
    tags: ["game", "gaming", "experience", "esports"],
    location: "펍지성수",
    address: "서울 성동구 연무장15길 11 펍지성수",
    coordinates: { longitude: 127.0563, latitude: 37.5445 },
    period_start: "2026-01-17",
    period_end: "2026-02-27",
    operating_hours: "10:00 - 22:00",
    description: "배틀그라운드 PUBG 게임 체험 팝업. 윈터스쿨 특별 이벤트.",
    description_ja: "バトルグラウンドPUBGゲーム体験ポップアップ。ウィンタースクール特別イベント。",
    description_en: "PUBG Battlegrounds game experience popup. Winter School special event.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "10",
    name: "Dessert Gems",
    name_korean: "디저트젬스",
    brand: "Dessert Gems",
    category: "food",
    tags: ["dessert", "bakery", "sweets", "F&B"],
    location: "성수동",
    address: "서울 성동구 연무장7길 7",
    coordinates: { longitude: 127.0554, latitude: 37.5438 },
    period_start: "2026-01-17",
    period_end: "2026-02-22",
    operating_hours: "11:00 - 20:00",
    description: "디저트젬스 디저트 팝업스토어. 보석같은 디저트를 만나보세요.",
    description_ja: "デザートジェムズのデザートポップアップストア。宝石のようなデザートに出会えます。",
    description_en: "Dessert Gems dessert popup store. Meet gem-like desserts.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "11",
    name: "Adidas Motorsport",
    name_korean: "아디다스 모터스포츠",
    brand: "Adidas",
    category: "fashion",
    tags: ["sports", "fashion", "motorsport", "apparel"],
    location: "무신사스토어성수",
    address: "서울 성동구 왕십리로 83 무신사스토어성수",
    coordinates: { longitude: 127.0434, latitude: 37.5442 },
    period_start: "2026-01-16",
    period_end: "2026-02-04",
    operating_hours: "11:00 - 21:00",
    description: "아디다스 모터스포츠 라인 팝업. 한정판 제품 판매.",
    description_ja: "アディダスモータースポーツラインポップアップ。限定版製品販売。",
    description_en: "Adidas Motorsport line popup. Limited edition products for sale.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1556906781-9a412961c28c?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "12",
    name: "BLR at Musinsa Store",
    name_korean: "비엘알",
    brand: "BLR",
    category: "fashion",
    tags: ["fashion", "streetwear", "korean"],
    location: "무신사스토어성수",
    address: "서울 성동구 왕십리로 83 무신사스토어성수",
    coordinates: { longitude: 127.0434, latitude: 37.5442 },
    period_start: "2026-01-16",
    period_end: "2026-02-04",
    operating_hours: "11:00 - 21:00",
    description: "BLR 스트릿웨어 브랜드 팝업. 무신사스토어 성수점.",
    description_ja: "BLRストリートウェアブランドポップアップ。ムシンサストア聖水店。",
    description_en: "BLR streetwear brand popup at Musinsa Store Seongsu.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1523398002811-999ca8dec234?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "13",
    name: "Two Maps Exhibition",
    name_korean: "두 개의 지도",
    brand: "LCDC",
    category: "art",
    tags: ["exhibition", "art", "gallery"],
    location: "LCDC",
    address: "서울 성동구 연무장5길 7 LCDC",
    coordinates: { longitude: 127.0537, latitude: 37.5441 },
    period_start: "2026-01-15",
    period_end: "2026-02-03",
    operating_hours: "10:00 - 19:00",
    description: "두 개의 지도 전시회. LCDC 갤러리에서 진행.",
    description_ja: "「二つの地図」展示会。LCDCギャラリーで開催。",
    description_en: "Two Maps Exhibition at LCDC Gallery.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1531243269054-5ebf6f34081e?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "14",
    name: "Alpha Drive One",
    name_korean: "알파드라이브원",
    brand: "Idol Group",
    category: "entertainment",
    tags: ["idol", "kpop", "merchandise"],
    location: "올리브영N성수",
    address: "서울 성동구 왕십리로 115 올리브영N성수",
    coordinates: { longitude: 127.0535, latitude: 37.5462 },
    period_start: "2026-01-13",
    period_end: "2026-01-31",
    operating_hours: "10:00 - 22:00",
    description: "아이돌 그룹 알파드라이브원 팝업. 올리브영N성수에서 진행.",
    description_ja: "アイドルグループ「アルファドライブワン」ポップアップ。オリーブヤングN聖水で開催。",
    description_en: "Idol group Alpha Drive One popup at Olive Young N Seongsu.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "15",
    name: "Bio Heal Boh",
    name_korean: "바이오힐보",
    brand: "Bio Heal Boh",
    category: "cosmetics",
    tags: ["beauty", "skincare", "cosmetics"],
    location: "올리브영N성수",
    address: "서울 성동구 왕십리로 115 올리브영N성수",
    coordinates: { longitude: 127.0535, latitude: 37.5462 },
    period_start: "2026-01-10",
    period_end: "2026-03-31",
    operating_hours: "10:00 - 22:00",
    description: "바이오힐보 뷰티 브랜드 팝업. 스킨케어 체험 가능.",
    description_ja: "バイオヒールボービューティーブランドポップアップ。スキンケア体験が可能。",
    description_en: "Bio Heal Boh beauty brand popup. Skincare experience available.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1571781926291-c477ebfd024b?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "16",
    name: "Lorena Canals at EQL",
    name_korean: "로레나카날",
    brand: "Lorena Canals",
    category: "lifestyle",
    tags: ["living", "interior", "home"],
    location: "EQL성수",
    address: "서울 성동구 연무장길 7 EQL성수",
    coordinates: { longitude: 127.0556, latitude: 37.5439 },
    period_start: "2026-01-06",
    period_end: "2026-02-02",
    operating_hours: "11:00 - 21:00",
    description: "로레나카날 리빙 브랜드 팝업. 인테리어 소품 전시 및 판매.",
    description_ja: "ロレナカナルのリビングブランドポップアップ。インテリア小物の展示と販売。",
    description_en: "Lorena Canals living brand popup. Interior goods exhibition and sale.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "17",
    name: "Omni People Vintage",
    name_korean: "옴니피플",
    brand: "Omni People",
    category: "fashion",
    tags: ["vintage", "fashion", "secondhand"],
    location: "EQL성수 2층",
    address: "서울 성동구 연무장길 7 EQL성수 2층",
    coordinates: { longitude: 127.0556, latitude: 37.5439 },
    period_start: "2026-01-06",
    period_end: "2026-02-05",
    operating_hours: "11:00 - 21:00",
    description: "옴니피플 빈티지 패션 팝업. 레트로 감성 아이템.",
    description_ja: "オムニピープルのヴィンテージファッションポップアップ。レトロ感性アイテム。",
    description_en: "Omni People vintage fashion popup. Retro sensibility items.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1558171813-4c088753af8f?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "18",
    name: "Lucky Mansion",
    name_korean: "행운맨숀",
    brand: "Made By",
    category: "entertainment",
    tags: ["character", "merchandise", "cute"],
    location: "메이드바이",
    address: "서울 성동구 서울숲2길 32-14",
    coordinates: { longitude: 127.0468, latitude: 37.5445 },
    period_start: "2026-01-06",
    period_end: "2026-04-07",
    operating_hours: "11:00 - 20:00",
    description: "행운맨숀 캐릭터 굿즈 팝업스토어.",
    description_ja: "ラッキーマンションのキャラクターグッズポップアップストア。",
    description_en: "Lucky Mansion character goods popup store.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1531747118685-ca8fa6e08806?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "19",
    name: "NEXT WAVE Market",
    name_korean: "NEXT WAVE",
    brand: "NEXT WAVE",
    category: "lifestyle",
    tags: ["market", "shopping", "lifestyle"],
    location: "성수동",
    address: "서울 성동구 연무장길 73",
    coordinates: { longitude: 127.0560, latitude: 37.5443 },
    period_start: "2026-12-24",
    period_end: "2026-02-14",
    operating_hours: "11:00 - 20:00",
    description: "NEXT WAVE 마켓 팝업. 다양한 브랜드 상품 판매.",
    description_ja: "NEXT WAVEマーケットポップアップ。様々なブランド商品を販売。",
    description_en: "NEXT WAVE market popup. Various brand products for sale.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "20",
    name: "Where's Wally Exhibition",
    name_korean: "월리를찾아라",
    brand: "The Seoul Lightium",
    category: "art",
    tags: ["exhibition", "interactive", "family"],
    location: "더서울라이티움",
    address: "서울 성동구 왕십리로 83-21 더서울라이티움",
    coordinates: { longitude: 127.0434, latitude: 37.5442 },
    period_start: "2026-12-22",
    period_end: "2026-04-05",
    operating_hours: "10:00 - 20:00",
    description: "월리를 찾아라 전시회. 인터랙티브 체험 가능.",
    description_ja: "「ウォーリーをさがせ！」展示会。インタラクティブ体験が可能。",
    description_en: "Where's Wally Exhibition. Interactive experience available.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1605721911519-3dfeb3be25e7?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "21",
    name: "For My Next Chapter",
    name_korean: "포 마이 넥스트 챕터",
    brand: "T Factory",
    category: "lifestyle",
    tags: ["telecom", "experience", "tech"],
    location: "T팩토리 성수",
    address: "서울 성동구 왕십리로 83-21 T팩토리",
    coordinates: { longitude: 127.0434, latitude: 37.5442 },
    period_start: "2026-12-21",
    period_end: "2026-02-22",
    operating_hours: "10:00 - 21:00",
    description: "SK텔레콤 T팩토리 체험 팝업. 미래 기술 체험 가능.",
    description_ja: "SKテレコムTファクトリー体験ポップアップ。未来技術の体験が可能。",
    description_en: "SK Telecom T Factory experience popup. Future technology experience available.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "22",
    name: "Lenovo Experience",
    name_korean: "레노버",
    brand: "Lenovo",
    category: "lifestyle",
    tags: ["IT", "tech", "computer", "experience"],
    location: "LCDC 3층",
    address: "서울 성동구 연무장5길 7 LCDC 3층",
    coordinates: { longitude: 127.0537, latitude: 37.5441 },
    period_start: "2026-12-02",
    period_end: "2026-06-30",
    operating_hours: "10:00 - 19:00",
    description: "레노버 IT 체험 팝업. 최신 제품 체험 가능.",
    description_ja: "レノボIT体験ポップアップ。最新製品の体験が可能。",
    description_en: "Lenovo IT experience popup. Latest product experience available.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1496181133206-80ce9b88a853?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "23",
    name: "Aspects of Love",
    name_korean: "사랑의 단상",
    brand: "Ttukseom Art Museum",
    category: "art",
    tags: ["exhibition", "art", "museum"],
    location: "뚝섬미술관",
    address: "서울 성동구 왕십리로 115 뚝섬미술관",
    coordinates: { longitude: 127.0535, latitude: 37.5462 },
    period_start: "2026-11-08",
    period_end: "2026-03-22",
    operating_hours: "10:00 - 19:00",
    description: "사랑의 단상 전시회. 뚝섬미술관에서 진행.",
    description_ja: "「愛の断想」展示会。トゥクソム美術館で開催。",
    description_en: "Aspects of Love Exhibition at Ttukseom Art Museum.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1578926375605-eaf7559b1458?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "24",
    name: "Prafpotu Perfume",
    name_korean: "프라포투투",
    brand: "Prafpotu",
    category: "cosmetics",
    tags: ["perfume", "fragrance", "beauty"],
    location: "LCDC",
    address: "서울 성동구 연무장5길 7 LCDC",
    coordinates: { longitude: 127.0537, latitude: 37.5441 },
    period_start: "2026-11-01",
    period_end: "2026-01-31",
    operating_hours: "10:00 - 19:00",
    description: "프라포투투 향수 팝업. 시그니처 향수 체험.",
    description_ja: "プラポトゥトゥの香水ポップアップ。シグネチャー香水を体験。",
    description_en: "Prafpotu perfume popup. Signature fragrance experience.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1541643600914-78b084683601?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "25",
    name: "Torriden Connect",
    name_korean: "토리든 솔리빌리지",
    brand: "Torriden",
    category: "cosmetics",
    tags: ["beauty", "skincare", "experience"],
    location: "토리든커넥트",
    address: "서울 성동구 서울숲2길 44",
    coordinates: { longitude: 127.0433, latitude: 37.5461 },
    period_start: "2026-10-21",
    period_end: "2026-01-31",
    operating_hours: "11:00 - 20:00",
    description: "토리든 스킨케어 브랜드 체험 팝업.",
    description_ja: "トリデンスキンケアブランド体験ポップアップ。",
    description_en: "Torriden skincare brand experience popup.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1608248597279-f99d160bfcbc?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
  {
    id: "26",
    name: "Taste House 2",
    name_korean: "취향가옥2",
    brand: "D Museum",
    category: "art",
    tags: ["exhibition", "art", "lifestyle"],
    location: "디뮤지엄",
    address: "서울 성동구 왕십리로 83-21 디뮤지엄",
    coordinates: { longitude: 127.0434, latitude: 37.5442 },
    period_start: "2026-06-28",
    period_end: "2026-02-22",
    operating_hours: "10:00 - 18:00",
    description: "취향가옥2 전시회. 라이프스타일과 아트의 만남.",
    description_ja: "「趣味の家2」展示会。ライフスタイルとアートの出会い。",
    description_en: "Taste House 2 Exhibition. Lifestyle meets art.",
    images: [],
    thumbnail_url: "https://images.unsplash.com/photo-1518998053901-5348d3961a04?w=400&h=300&fit=crop",
    source_post_url: "",
    is_active: true,
    created_at: new Date().toISOString(),
    updated_at: new Date().toISOString(),
  },
];

export function getPopupById(id: string): PopupStore | null {
  return SAMPLE_POPUPS.find((p) => p.id === id) || null;
}

export function filterPopups(options: {
  category?: string;
  search?: string;
  activeOnly?: boolean;
}): PopupStore[] {
  let filtered = [...SAMPLE_POPUPS];

  if (options.category) {
    filtered = filtered.filter((p) => p.category === options.category);
  }

  if (options.search) {
    const search = options.search.toLowerCase();
    filtered = filtered.filter(
      (p) =>
        p.name.toLowerCase().includes(search) ||
        p.name_korean.includes(search) ||
        p.brand.toLowerCase().includes(search) ||
        p.description.includes(search)
    );
  }

  if (options.activeOnly !== false) {
    filtered = filtered.filter((p) => p.is_active);
  }

  return filtered;
}
